# Crowdin configuration file - Smuppy Mobile
# https://support.crowdin.com/configuration-file/

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  # Auth namespace - Authentication flows
  - source: "/src/i18n/locales/en/auth.json"
    translation: "/src/i18n/locales/%two_letters_code%/auth.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Common namespace - Shared UI elements
  - source: "/src/i18n/locales/en/common.json"
    translation: "/src/i18n/locales/%two_letters_code%/common.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Feed namespace - Feed, posts, comments
  - source: "/src/i18n/locales/en/feed.json"
    translation: "/src/i18n/locales/%two_letters_code%/feed.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Profile namespace - User profiles
  - source: "/src/i18n/locales/en/profile.json"
    translation: "/src/i18n/locales/%two_letters_code%/profile.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Settings namespace - App settings
  - source: "/src/i18n/locales/en/settings.json"
    translation: "/src/i18n/locales/%two_letters_code%/settings.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Messages namespace - Chat, conversations
  - source: "/src/i18n/locales/en/messages.json"
    translation: "/src/i18n/locales/%two_letters_code%/messages.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Notifications namespace - Push notifications, in-app
  - source: "/src/i18n/locales/en/notifications.json"
    translation: "/src/i18n/locales/%two_letters_code%/notifications.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Errors namespace - Error messages
  - source: "/src/i18n/locales/en/errors.json"
    translation: "/src/i18n/locales/%two_letters_code%/errors.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Onboarding namespace - User onboarding flow
  - source: "/src/i18n/locales/en/onboarding.json"
    translation: "/src/i18n/locales/%two_letters_code%/onboarding.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Sessions namespace - Private sessions
  - source: "/src/i18n/locales/en/sessions.json"
    translation: "/src/i18n/locales/%two_letters_code%/sessions.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Payments namespace - Payments, wallet
  - source: "/src/i18n/locales/en/payments.json"
    translation: "/src/i18n/locales/%two_letters_code%/payments.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Peaks namespace - Short videos
  - source: "/src/i18n/locales/en/peaks.json"
    translation: "/src/i18n/locales/%two_letters_code%/peaks.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
    
  # Disputes namespace - Dispute resolution
  - source: "/src/i18n/locales/en/disputes.json"
    translation: "/src/i18n/locales/%two_letters_code%/disputes.json"
    languages_mapping:
      two_letters_code:
        "pt-BR": "pt-BR"
        "ar": "ar"
    update_option: "update_as_unapproved"
