/**
 * Shared expertise categories for Pro Creator accounts.
 * Used by both onboarding (ExpertiseScreen) and settings (EditExpertiseScreen).
 * Single source of truth — edit here, both screens update.
 */

import type { CategoryConfig } from './category-types';
import { cat, item } from './category-helpers';

export const ALL_EXPERTISE: CategoryConfig[] = [
  cat('Personal Training', 'barbell', '#FF6B6B', [
    item('General Fitness', 'fitness-outline', '#FF6B6B'),
    item('Weight Loss', 'scale-outline', '#4ECDC4'),
    item('Muscle Building', 'barbell-outline', '#34495E'),
    item('Strength Training', 'barbell', '#E74C3C'),
    item('Body Transformation', 'trending-up-outline', '#FF4081'),
    item('Toning', 'body-outline', '#9C27B0'),
    item('Endurance', 'heart-outline', '#F44336'),
    item('Flexibility', 'resize-outline', '#8BC34A'),
  ]),
  cat('Yoga & Pilates', 'leaf', '#1ABC9C', [
    item('Hatha Yoga', 'leaf-outline', '#1ABC9C'),
    item('Vinyasa Flow', 'water-outline', '#00BCD4'),
    item('Power Yoga', 'flash-outline', '#FF5722'),
    item('Yin Yoga', 'moon-outline', '#673AB7'),
    item('Hot Yoga', 'flame-outline', '#FF9800'),
    item('Mat Pilates', 'body-outline', '#E91E63'),
    item('Reformer Pilates', 'fitness-outline', '#9C27B0'),
    item('Prenatal Yoga', 'heart-circle-outline', '#EC407A'),
  ]),
  cat('Nutrition & Diet', 'nutrition', '#27AE60', [
    item('Sports Nutrition', 'nutrition-outline', '#27AE60'),
    item('Weight Management', 'scale-outline', '#4ECDC4'),
    item('Meal Planning', 'restaurant-outline', '#FF9800'),
    item('Supplements', 'medical-outline', '#3498DB'),
    item('Keto/Low Carb', 'leaf-outline', '#8BC34A'),
    item('Vegan/Plant-Based', 'leaf', '#4CAF50'),
    item('Gut Health', 'fitness-outline', '#9C27B0'),
    item('Performance Nutrition', 'rocket-outline', '#FF5722'),
  ]),
  cat('Group Fitness', 'people', '#F39C12', [
    item('HIIT Classes', 'flash-outline', '#E67E22'),
    item('CrossFit', 'flame-outline', '#FF5722'),
    item('Spin/Cycling', 'bicycle-outline', '#795548'),
    item('Bootcamp', 'people-outline', '#4CAF50'),
    item('Circuit Training', 'sync-outline', '#00ACC1'),
    item('Aerobics', 'heart-outline', '#E91E63'),
    item('Step Classes', 'trending-up-outline', '#FF4081'),
    item('Aqua Fitness', 'water-outline', '#0288D1'),
  ]),
  cat('Combat Sports', 'flash', '#D32F2F', [
    item('Boxing', 'fitness-outline', '#D32F2F'),
    item('MMA', 'flash', '#E64A19'),
    item('Kickboxing', 'flash-outline', '#FF5722'),
    item('Muay Thai', 'fitness', '#FF7043'),
    item('BJJ/Jiu-Jitsu', 'body-outline', '#388E3C'),
    item('Wrestling', 'people', '#607D8B'),
    item('Karate', 'hand-right-outline', '#F57C00'),
    item('Judo', 'body', '#1976D2'),
  ]),
  cat('Mind & Wellness', 'happy', '#9B59B6', [
    item('Meditation', 'leaf-outline', '#9B59B6'),
    item('Breathwork', 'cloudy-outline', '#00ACC1'),
    item('Mindfulness', 'flower-outline', '#E91E63'),
    item('Stress Management', 'heart-outline', '#F44336'),
    item('Sleep Coaching', 'moon-outline', '#3F51B5'),
    item('Life Coaching', 'bulb-outline', '#FF9800'),
    item('Mental Performance', 'bulb-outline', '#673AB7'),
    item('Relaxation', 'happy-outline', '#4CAF50'),
  ]),
  cat('Sports Coaching', 'trophy', '#FFD700', [
    item('Running Coach', 'walk-outline', '#2196F3'),
    item('Swimming Coach', 'water-outline', '#00BCD4'),
    item('Tennis Coach', 'tennisball-outline', '#C5E063'),
    item('Golf Instructor', 'golf-outline', '#228B22'),
    item('Football Coach', 'football-outline', '#8B4513'),
    item('Basketball Coach', 'basketball-outline', '#FF6B35'),
    item('Triathlon Coach', 'ribbon-outline', '#9C27B0'),
    item('Cycling Coach', 'bicycle-outline', '#795548'),
  ]),
  cat('Rehabilitation', 'medkit', '#3498DB', [
    item('Injury Prevention', 'shield-outline', '#4CAF50'),
    item('Post-Surgery Rehab', 'medkit-outline', '#3498DB'),
    item('Sports Injury', 'bandage-outline', '#FF9800'),
    item('Back Pain', 'body-outline', '#F44336'),
    item('Joint Mobility', 'sync-outline', '#00ACC1'),
    item('Corrective Exercise', 'checkmark-circle-outline', '#4ECDC4'),
    item('Chronic Pain', 'pulse-outline', '#9C27B0'),
    item('Physical Therapy', 'fitness-outline', '#2196F3'),
  ]),
  cat('Dance & Movement', 'musical-notes', '#E91E63', [
    item('Hip Hop', 'musical-notes', '#212121'),
    item('Contemporary', 'body-outline', '#607D8B'),
    item('Ballet', 'body', '#9C27B0'),
    item('Latin Dance', 'musical-notes-outline', '#FF9800'),
    item('Zumba', 'happy-outline', '#FF5722'),
    item('Pole Dance', 'barbell-outline', '#FF4081'),
    item('Aerial Arts', 'airplane-outline', '#00BCD4'),
    item('Barre', 'body-outline', '#E91E63'),
  ]),
  cat('Outdoor & Adventure', 'trail-sign', '#5D4037', [
    item('Hiking Guide', 'trail-sign-outline', '#5D4037'),
    item('Rock Climbing', 'trending-up-outline', '#795548'),
    item('Surf Instructor', 'water-outline', '#0288D1'),
    item('Ski/Snowboard', 'snow-outline', '#42A5F5'),
    item('Kayak/Paddle', 'boat-outline', '#00897B'),
    item('Trail Running', 'walk-outline', '#4CAF50'),
    item('Mountain Biking', 'bicycle-outline', '#795548'),
    item('Outdoor Fitness', 'sunny-outline', '#FFC107'),
  ]),
  cat('Specialized Populations', 'star', '#9C27B0', [
    item('Senior Fitness', 'people-outline', '#5C6BC0'),
    item('Pre/Postnatal', 'heart-circle-outline', '#EC407A'),
    item('Youth/Kids', 'happy-outline', '#FF9800'),
    item('Athletes', 'trophy-outline', '#FFD700'),
    item('Beginners', 'star-outline', '#4CAF50'),
    item('Disabled/Adaptive', 'accessibility-outline', '#2196F3'),
    item('Women\'s Fitness', 'female-outline', '#E91E63'),
    item('Men\'s Health', 'male-outline', '#1976D2'),
  ]),
  cat('Functional Training', 'sync', '#00ACC1', [
    item('Functional Movement', 'sync-outline', '#00ACC1'),
    item('Mobility Work', 'resize-outline', '#8BC34A'),
    item('Core Training', 'fitness-outline', '#FF5722'),
    item('Balance Training', 'scale-outline', '#9C27B0'),
    item('Stability', 'shield-outline', '#607D8B'),
    item('Kettlebells', 'barbell-outline', '#795548'),
    item('TRX/Suspension', 'git-branch-outline', '#FF9800'),
    item('Bodyweight', 'body-outline', '#4CAF50'),
  ]),
  cat('Wellness Services', 'sparkles', '#00BCD4', [
    item('Massage Therapy', 'hand-left-outline', '#8BC34A'),
    item('Recovery Specialist', 'bandage-outline', '#00BCD4'),
    item('Stretching Coach', 'resize-outline', '#FF9800'),
    item('Foam Rolling', 'disc-outline', '#607D8B'),
    item('Cryotherapy', 'snow-outline', '#2196F3'),
    item('Sauna/Heat', 'flame-outline', '#FF5722'),
  ]),
  cat('Performance', 'rocket', '#FF5722', [
    item('Speed Training', 'flash-outline', '#F44336'),
    item('Agility', 'sync-outline', '#FF9800'),
    item('Power Training', 'rocket-outline', '#FF5722'),
    item('Plyometrics', 'arrow-up-outline', '#E91E63'),
    item('Sport-Specific', 'trophy-outline', '#FFD700'),
    item('Competition Prep', 'ribbon-outline', '#9C27B0'),
  ]),
  cat('Online Coaching', 'videocam', '#2196F3', [
    item('Virtual Training', 'videocam-outline', '#2196F3'),
    item('Program Design', 'document-outline', '#607D8B'),
    item('Online Classes', 'laptop-outline', '#00ACC1'),
    item('App-Based Coaching', 'phone-portrait-outline', '#4CAF50'),
    item('Remote Nutrition', 'nutrition-outline', '#FF9800'),
    item('Video Analysis', 'videocam', '#9C27B0'),
  ]),
  cat('Lifestyle & Habits', 'sunny', '#FFC107', [
    item('Habit Coaching', 'checkmark-circle-outline', '#4CAF50'),
    item('Time Management', 'time-outline', '#607D8B'),
    item('Work-Life Balance', 'scale-outline', '#2196F3'),
    item('Motivation', 'rocket-outline', '#FF5722'),
    item('Goal Setting', 'flag-outline', '#E91E63'),
    item('Accountability', 'people-outline', '#9C27B0'),
  ]),
  cat('Combat Fitness', 'fitness', '#E64A19', [
    item('Cardio Boxing', 'fitness-outline', '#E64A19'),
    item('Martial Arts Fitness', 'flash-outline', '#FF5722'),
    item('Self-Defense', 'shield-outline', '#607D8B'),
    item('Combat Conditioning', 'barbell-outline', '#D32F2F'),
  ]),
  cat('Aquatic Sports', 'water', '#0288D1', [
    item('Swim Coaching', 'water-outline', '#0288D1'),
    item('Pool Fitness', 'water', '#00ACC1'),
    item('Diving', 'boat-outline', '#0277BD'),
    item('Water Sports', 'boat', '#00897B'),
  ]),
  cat('Stretching & Flexibility', 'resize', '#8BC34A', [
    item('Static Stretching', 'resize-outline', '#8BC34A'),
    item('Dynamic Stretching', 'sync-outline', '#4CAF50'),
    item('PNF Stretching', 'fitness-outline', '#00ACC1'),
    item('Fascial Release', 'disc-outline', '#9C27B0'),
    item('Splits Training', 'body-outline', '#E91E63'),
    item('Contortion', 'sync', '#FF5722'),
  ]),
  cat('Corporate Wellness', 'business', '#607D8B', [
    item('Office Fitness', 'business-outline', '#607D8B'),
    item('Desk Exercises', 'desktop-outline', '#00ACC1'),
    item('Team Building', 'people-outline', '#4CAF50'),
    item('Stress Workshops', 'bulb-outline', '#FF9800'),
    item('Ergonomics', 'body-outline', '#2196F3'),
    item('Lunch & Learn', 'restaurant-outline', '#E91E63'),
  ]),
  cat('Holistic Health', 'globe', '#4ECDC4', [
    item('Ayurveda', 'leaf-outline', '#FF9800'),
    item('Traditional Medicine', 'medical-outline', '#4CAF50'),
    item('Energy Healing', 'flash-outline', '#9C27B0'),
    item('Acupressure', 'hand-left-outline', '#2196F3'),
    item('Reflexology', 'footsteps-outline', '#E91E63'),
    item('Aromatherapy', 'flower-outline', '#FF5722'),
  ]),
  cat('Mind-Body Integration', 'flower', '#673AB7', [
    item('Tai Chi', 'body-outline', '#607D8B'),
    item('Qigong', 'leaf-outline', '#4CAF50'),
    item('Feldenkrais', 'sync-outline', '#00ACC1'),
    item('Alexander Technique', 'body', '#9C27B0'),
    item('Somatic Movement', 'fitness-outline', '#E91E63'),
    item('Body Awareness', 'eye-outline', '#2196F3'),
  ]),
  cat('Weight Management', 'scale', '#4ECDC4', [
    item('Fat Loss Specialist', 'trending-down-outline', '#4ECDC4'),
    item('Metabolism Coach', 'flash-outline', '#FF9800'),
    item('Body Composition', 'scale-outline', '#607D8B'),
    item('Calorie Management', 'calculator-outline', '#2196F3'),
    item('Macro Coaching', 'pie-chart-outline', '#9C27B0'),
    item('Sustainable Weight', 'leaf-outline', '#4CAF50'),
  ]),
  cat('Extreme Sports', 'rocket', '#FF5722', [
    item('Parkour', 'walk-outline', '#607D8B'),
    item('Skateboarding', 'disc-outline', '#795548'),
    item('BMX/Cycling', 'bicycle-outline', '#FF5722'),
    item('Obstacle Course', 'flag-outline', '#E91E63'),
    item('Adventure Racing', 'trophy-outline', '#FFD700'),
    item('Crossfit Games', 'flame-outline', '#D32F2F'),
  ]),
];
