/**
 * Shared interest categories for Personal accounts.
 * Used by both onboarding (InterestsScreen) and settings (EditInterestsScreen).
 * Single source of truth — edit here, both screens update.
 */

import type { CategoryConfig } from './category-types';
import { cat, item } from './category-helpers';

export const ALL_INTERESTS: CategoryConfig[] = [
  cat('Sports', 'football', '#FF6B35', [
    item('Football', 'football', '#8B4513'),
    item('Basketball', 'basketball', '#FF6B35'),
    item('Tennis', 'tennisball', '#C5E063'),
    item('Swimming', 'water', '#0099CC'),
    item('Running', 'walk', '#FF5722'),
    item('Cycling', 'bicycle', '#E63946'),
    item('Golf', 'golf', '#228B22'),
    item('Volleyball', 'basketball-outline', '#FFC107'),
  ]),
  cat('Fitness', 'barbell', '#1E90FF', [
    item('Gym', 'barbell', '#1E90FF'),
    item('CrossFit', 'fitness', '#FF4500'),
    item('Weightlifting', 'barbell-outline', '#2F4F4F'),
    item('Cardio', 'heart', '#FF1493'),
    item('HIIT', 'flash', '#FF6347'),
    item('Calisthenics', 'body', '#20B2AA'),
    item('Pilates', 'fitness-outline', '#E91E63'),
    item('Stretching', 'resize', '#8BC34A'),
  ]),
  cat('Wellness', 'leaf', '#27AE60', [
    item('Yoga', 'body', '#9B59B6'),
    item('Meditation', 'leaf', '#27AE60'),
    item('Nutrition', 'nutrition', '#FF9800'),
    item('Spa & Recovery', 'sparkles', '#00BCD4'),
    item('Mental Health', 'happy', '#607D8B'),
    item('Sleep', 'moon', '#3F51B5'),
    item('Mindfulness', 'flower', '#E91E63'),
    item('Breathwork', 'cloudy', '#00ACC1'),
  ]),
  cat('Outdoor', 'trail-sign', '#5D4037', [
    item('Hiking', 'trail-sign', '#5D4037'),
    item('Climbing', 'trending-up', '#795548'),
    item('Surfing', 'water', '#0288D1'),
    item('Skiing', 'snow', '#42A5F5'),
    item('Camping', 'bonfire', '#FF7043'),
    item('Trail Running', 'walk', '#4CAF50'),
    item('Mountain Biking', 'bicycle', '#795548'),
    item('Kayaking', 'boat', '#00897B'),
  ]),
  cat('Combat Sports', 'flash', '#D32F2F', [
    item('Boxing', 'fitness', '#DC143C'),
    item('MMA', 'fitness', '#D32F2F'),
    item('Judo', 'body', '#1976D2'),
    item('Karate', 'hand-right', '#F57C00'),
    item('Taekwondo', 'flash', '#7B1FA2'),
    item('BJJ', 'body-outline', '#388E3C'),
    item('Kickboxing', 'fitness-outline', '#E64A19'),
    item('Muay Thai', 'flash-outline', '#FF5722'),
  ]),
  cat('Water Sports', 'water', '#0288D1', [
    item('Scuba Diving', 'water', '#0277BD'),
    item('Snorkeling', 'water-outline', '#00ACC1'),
    item('Wakeboarding', 'boat', '#0288D1'),
    item('Water Polo', 'water', '#1976D2'),
    item('Paddle Board', 'boat', '#00BCD4'),
    item('Sailing', 'boat', '#0097A7'),
    item('Kitesurfing', 'flash', '#03A9F4'),
    item('Rowing', 'boat-outline', '#455A64'),
  ]),
  cat('Team Sports', 'people', '#4CAF50', [
    item('Rugby', 'american-football', '#8D6E63'),
    item('Hockey', 'disc', '#607D8B'),
    item('Handball', 'basketball', '#FF7043'),
    item('Cricket', 'baseball', '#8BC34A'),
    item('Baseball', 'baseball', '#D32F2F'),
    item('Softball', 'baseball-outline', '#FF9800'),
    item('Lacrosse', 'disc-outline', '#9C27B0'),
    item('Futsal', 'football-outline', '#4CAF50'),
  ]),
  cat('Racket Sports', 'tennisball', '#C5E063', [
    item('Badminton', 'tennisball-outline', '#4CAF50'),
    item('Squash', 'tennisball', '#2196F3'),
    item('Table Tennis', 'disc', '#FF5722'),
    item('Padel', 'tennisball', '#9C27B0'),
    item('Pickleball', 'tennisball-outline', '#00BCD4'),
    item('Racquetball', 'tennisball', '#FF9800'),
  ]),
  cat('Dance', 'musical-notes', '#E91E63', [
    item('Hip Hop', 'musical-notes', '#212121'),
    item('Salsa', 'musical-notes-outline', '#E91E63'),
    item('Ballet', 'body-outline', '#9C27B0'),
    item('Contemporary', 'body', '#607D8B'),
    item('Zumba', 'happy', '#FF5722'),
    item('Breakdance', 'flash', '#F44336'),
    item('Pole Dance', 'barbell-outline', '#FF4081'),
    item('Latin Dance', 'musical-notes', '#FF9800'),
  ]),
  cat('Mind & Body', 'flower', '#9B59B6', [
    item('Tai Chi', 'body-outline', '#607D8B'),
    item('Qigong', 'leaf-outline', '#4CAF50'),
    item('Relaxation', 'flower-outline', '#E91E63'),
    item('Stress Relief', 'heart-outline', '#F44336'),
    item('Self-Care', 'sunny-outline', '#FFC107'),
    item('Holistic Health', 'globe-outline', '#00BCD4'),
  ]),
  cat('Extreme Sports', 'rocket', '#FF5722', [
    item('Skateboarding', 'disc', '#795548'),
    item('BMX', 'bicycle', '#FF5722'),
    item('Parkour', 'walk', '#607D8B'),
    item('Skydiving', 'airplane', '#2196F3'),
    item('Bungee Jumping', 'arrow-down', '#E91E63'),
    item('Snowboarding', 'snow', '#00BCD4'),
    item('Motocross', 'speedometer', '#F44336'),
    item('Paragliding', 'airplane-outline', '#9C27B0'),
  ]),
  cat('Lifestyle', 'sunny', '#FFC107', [
    item('Healthy Eating', 'restaurant', '#4CAF50'),
    item('Active Living', 'walk', '#2196F3'),
    item('Work-Life Balance', 'scale', '#607D8B'),
    item('Personal Growth', 'trending-up', '#9C27B0'),
    item('Motivation', 'rocket', '#FF5722'),
    item('Goal Setting', 'flag', '#E91E63'),
  ]),
  cat('Winter Sports', 'snow', '#42A5F5', [
    item('Alpine Skiing', 'snow', '#42A5F5'),
    item('Cross-Country Ski', 'walk', '#0288D1'),
    item('Ice Skating', 'snow-outline', '#00BCD4'),
    item('Ice Hockey', 'disc', '#607D8B'),
    item('Curling', 'disc-outline', '#795548'),
    item('Bobsled', 'speedometer', '#F44336'),
  ]),
  cat('Athletics', 'ribbon', '#FFD700', [
    item('Sprinting', 'flash', '#F44336'),
    item('Long Distance', 'walk', '#4CAF50'),
    item('Hurdles', 'trending-up', '#FF9800'),
    item('High Jump', 'arrow-up', '#2196F3'),
    item('Long Jump', 'arrow-forward', '#9C27B0'),
    item('Pole Vault', 'trending-up', '#795548'),
    item('Shot Put', 'disc', '#607D8B'),
    item('Javelin', 'arrow-forward-outline', '#FF5722'),
  ]),
  cat('Equestrian', 'paw', '#8D6E63', [
    item('Horse Riding', 'paw', '#8D6E63'),
    item('Dressage', 'ribbon', '#FFD700'),
    item('Show Jumping', 'trending-up', '#4CAF50'),
    item('Polo', 'disc', '#1976D2'),
  ]),
  cat('Recovery', 'medkit', '#3498DB', [
    item('Massage', 'hand-left', '#8BC34A'),
    item('Physiotherapy', 'bandage', '#3498DB'),
    item('Cryotherapy', 'snow', '#00BCD4'),
    item('Foam Rolling', 'resize', '#FF9800'),
    item('Sauna', 'flame', '#FF5722'),
    item('Ice Baths', 'water', '#2196F3'),
  ]),
];
